#!/usr/bin/env node
/**
 * Regenerates `src/generated/DokployClient.ts` from the vendored Dokploy OpenAPI document
 * at `.repos/dokploy/openapi.json`, after merging `openapi.codegen.patch.json` (security) with
 * `openapi.codegen.response-patch.json` (typed 200 bodies) and applying the result via `openapigen -p`.
 *
 * When Dokploy bumps the embedded spec under `.repos/dokploy/`, rerun from this directory:
 *
 * - `vp run codegen`
 *
 * then commit both the updated spec upstream (if you mirror it separately) **and**
 * `src/generated/DokployClient.ts`. If openapi paths change, refresh the patch JSON with
 *
 * - `node scripts/build-openapi-patch.mjs`
 *
 * before codegen so bogus per-operation `{ Authorization }` securities stay aligned with `apiKey`.
 *
 * CI can enforce cleanliness with `git diff --exit-code` after `vp run codegen`.
 */

import { execFileSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const pkgRoot = path.resolve(__dirname, "..");

const openapigenBin = path.join(pkgRoot, "node_modules/@effect/openapi-generator/dist/bin.js");
const specAbs = path.resolve(pkgRoot, "../../.repos/dokploy/openapi.json");
const patchFile = path.join(pkgRoot, "openapi.codegen.patch.json");
const responsePatchFile = path.join(pkgRoot, "openapi.codegen.response-patch.json");
const generatedPath = path.join(pkgRoot, "src/generated/DokployClient.ts");

fs.mkdirSync(path.dirname(generatedPath), { recursive: true });

for (const f of [specAbs, patchFile]) {
  if (!fs.existsSync(f)) throw new Error(`missing required file: ${f}`);
}

/** Merges security-only patch with hand-maintained response-schema ops so `build-openapi-patch.mjs` never strips the latter. */
const mergedPatchOps = [...JSON.parse(fs.readFileSync(patchFile, "utf8"))];
if (fs.existsSync(responsePatchFile)) {
  mergedPatchOps.push(...JSON.parse(fs.readFileSync(responsePatchFile, "utf8")));
}
const mergedPatchPath = path.join(pkgRoot, ".openapi.codegen.patch.merged.json");
fs.writeFileSync(mergedPatchPath, `${JSON.stringify(mergedPatchOps)}\n`);

const args = [
  "--spec",
  specAbs,
  "--format",
  "httpclient",
  "--name",
  "Dokploy",
  "--patch",
  mergedPatchPath,
];

/** @type {import("node:child_process").ExecFileSyncOptions} */
const execOpts = { encoding: "utf8", cwd: pkgRoot, maxBuffer: 256 * 1024 * 1024 };

/**
 * Stderr carries openapigen warnings; treat only non-zero exit as failure.
 */
try {
  const stdout = execFileSync(process.execPath, [openapigenBin, ...args], execOpts);
  const body = stdout.endsWith("\n") ? stdout : `${stdout}\n`;
  const banner = "// Generated by openapigen — do not edit by hand.\n\n";
  fs.writeFileSync(generatedPath, `${banner}${body}`);
  console.warn(`written ${generatedPath}`);
} finally {
  try {
    fs.unlinkSync(mergedPatchPath);
  } catch {
    /* ignore */
  }
}
